version: "3"

services:
  quarkus-imagebin:
    build: .
    environment:
      - DB_HOST=mysql-db
      - DB_DATABASE=imagebin
      - DB_USER=root
      - DB_PASS=123456
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - imagebin
  mysql-db:
    image: "mysql:5.7"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=imagebin
    command: --max_allowed_packet=16M
    ports:
      - "3306:3306"
    networks:
      - imagebin

networks:
  imagebin:
    driver: bridge

volumes:
  db-data: